version: '3.6'

services:
  postgres:
    restart: always
    image: sameersbn/postgresql:9.5-3
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - DB_USER=di
      - DB_PASS=di
      - DB_NAME=di
      - DB_EXTENSION="uuid-ossp"